dataset: Tree
n_lags: 3
device: 'cpu'

#hyperparameters:  
lr_G: 0.01
lr_E: 0.01 
batch_size: 256
gamma: 1
beta: 1

#embedding hyperparameter:
E_hidden_dim: 32
E_num_layers: 1
init_fixed: True
#generator hyperparameter:
G_input_dim: 1
G_hidden_dim: 32
G_num_layers: 1



comment: tree3